version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinyurl
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redislabs/rebloom
    ports:
      - "6379:6379"

volumes:
  postgres-data:
